@startuml
'https://plantuml.com/use-case-diagram

caption CC21-EDW
title Business Context

User as User
(View activities) as view #lightblue
(Export activities) as export #lightblue
(Record activities) as record #lightblue

frame "Event Driven Workflow"{
    (Synchronize activities) as synch #lightblue
    (Upload activities) as upload #lightblue
    (Store activities) as store #lightblue

    [Database] as [DB]
    [Event-Bus] as [Kafka]
    [File-System] as [Files]

    [Files] -- [Kafka]
    [Kafka] -- synch
    [Kafka] -- upload
    [Kafka] -- store
}


[Activity Portal] as ActivityPortal

User - record
ActivityPortal -- record

User -- synch
ActivityPortal -- synch

User -- view
ActivityPortal --- view

ActivityPortal -- upload

User - export
ActivityPortal --- export
Files --- export

DB -- store
@enduml