@startuml
'https://plantuml.com/use-case-diagram

User as User
(Record activity) as (Record)

frame "Event Driven Workflow"{
    (Synchronize activities) as (Synchronize)
    (Upload activities) as (Upload)
    (View activities) as (View)

    [Database] as [DB]
    [Event-Bus] as [Kafka]
    [File-System] as [Files]

    [DB] -- [Kafka]
    [Files] -- [Kafka]
    [Kafka] -- (Synchronize)
    [Kafka] -- (Upload)
}

(Export activity) as (Export)

[Runmeter-App] as [Runmeter]
[Strava Portal] as [Strava]
[Komoot-Portal] as [Komoot]

User - (Record)
[Strava] -- (Record)
[Runmeter] -- (Record)

User -- (Synchronize)
[Strava] -- (Synchronize)

User -- (View)
[Komoot] --- (View)

[Komoot] -- (Upload)

User - (Export)
[Runmeter] --- (Export)
[Files] --- (Export)
@enduml