@startuml
'https://plantuml.com/component-diagram

!include whitebox-components.pu!edw-core
!include whitebox-components.pu!workflow

[SportsRepo] --> WorkflowStatus
WorkflowStatus --> [WF-CC]
[StravaConnect] --> WorkflowStatus
[KomootConnect] --> WorkflowStatus
[FileConnect] --> WorkflowStatus

@enduml