@startuml
'https://plantuml.com/component-diagram

!include whitebox-components.pu!portals
!include whitebox-components.pu!edw-core

frame "Event Driven Workflow" {
    frame "Serverless"{
        [Serverless Platform] as [knative]
        () "Transformation" as transformation
        () "Validation" as validation
        knative O-- validation
        knative o-- transformation
    }
}

[SportsRepo] <-- DomainActivity : consume

[StravaConnect] --> [Strava] : get
StravaActivity <-- [StravaConnect] : publish

[FileConnect] --> runmeterFiles : load
StravaActivity <-- [FileConnect] : publish

validation <-- StravaActivity : consume
validation --> StravaActivityError : publish

transformation <-- StravaActivity : consume
transformation --> DomainActivity : publish

@enduml