@startuml
'https://plantuml.com/component-diagram

!include whitebox-components.pu!portals
!include whitebox-components.pu!edw-core
!include whitebox-components.pu!serverless

[SportsRepo] <-- DomainActivity : consume

[StravaConnect] --> [Strava] : get
StravaActivity <-- [StravaConnect] : publish

[FileConnect] --> runmeterFiles : load
StravaActivity <-- [FileConnect] : publish

transformation --> validation : call
transformation <-- StravaActivity : consume
transformation --> DomainActivity : publish
transformation --> StravaActivityError : publish

@enduml