@startuml
'https://plantuml.com/component-diagram

frame "Event Driven Workflow" {
  [Strava Portal] as [Strava]
  [Komoot Portal] as [Komoot]

  [Strava Connector] as [StravaConnect]
  [Kommoot Connector] as [KommootConnect]

  [Event-Bus] as [Kafka]

  [Sports-Repository] as [SportsRepo]

  [WorkflowControlCenter] as [WF-CC]

  [Kafka] -- WorkflowStatus
  [Kafka] -- KomootActivity
  [Kafka] -- StravaActivity
  [FileConnect]

  database "PostgreSQL" {
    frame "SPORTS" {
      [ACTIVITY]
    }
  }
}

[FileConnect] --> [Kafka]
[SportsRepo] --> [Kafka]
[WF-CC] --> WorkflowStatus

[StravaConnect] --> [Strava]
StravaActivity <-- [StravaConnect]
WorkflowStatus <-- [StravaConnect]

[KommootConnect] --> [Komoot]
KomootActivity <-- [KommootConnect]
WorkflowStatus <-- [KommootConnect]

[ACTIVITY] <-- [SportsRepo]

@enduml